### ISSUE TITLE
Cannot find the matrix --> dual quaternion translation formula 

### ISSUE THREAD

**Issue by olliglorioso** [chinedufn/mat4-to-dual-quat#1]
Hello,

Thanks for the library, seems amazing. I am trying to implement this in C++, but I did not find the exact formula in the paper you have provided. Can you point out exactly where the formula is in the paper?

**Comment by chinedufn** [comment]
Hey.

It's been a very long time since I'm implemented a `mat4 -> dual quat` conversion so I don't remember where I learned about the equations.

Best of luck finding some.
